### ISSUE TITLE
Client side sdk problem

### ISSUE THREAD

**Issue by bys42** [UnifiedID2/uid2docs#19]
Hello,
I'm trying to use client side SDK (uid2-sdk-0.0.1a.js) in https://github.com/UnifiedID2/uid2docs/blob/main/api/v1/sdks/client-side-identity-v1.md
It seems like there's a typo or compatibility issue that the SDK uses "advertisement_token" instead of "advertising_token" in getAdvertisingToken method but the endpoint returns "advertising_token".
Could you help me to check this? 
Thanks
Bys

**Comment by scong-ttd** [comment]
Hi Bys,

Your observation is correct. We had an internal update of endpoints while the js sdk is still using the old one.
Currently js sdk points to the old endpoint which returns both "advertisement_token" and "advertising_token" with the same value, we will upgrade it soon. Meanwhile nothing should break on this.
Are you having any trouble using UID2 tokens due to this naming difference?

Shawn

**Comment by bys42** [comment]
Hi Shawn,
Thanks for explanation. I notice this since getAdvertisingToken returns undefined after init, currently I add "advertisement_token" into the response from /token/generate to make it like old endpoint you mentioned and all looks good now.
Thanks
Bys
